### ISSUE TITLE
Editing `packman.json` or restoring packages results in: Could not load file or assembly 'Microsoft.JSON.Core, Version=14.0.0.0, (...)' or one of its dependencies.

### ISSUE THREAD

**Issue by ericwj** [madskristensen/Packman#48] opened 2018-03-31 15:45 UTC
### Installed product versions
- Visual Studio: 2017 15.7.0 Preview 2 and 2017 15.6.4
- This extension: 1.2.130
- Projects targeting .NET Core SDK 2.1.4, 2.1.300-preview1-008174

### Description
The extension is broken.

It will only download packages when they are added the first time. Restore packages or changing `packman.json` will always result in the error shown below in the **Show output from**: *Client-side Library Installer* window and nothing else.

### Steps to recreate
1. Install Client-Side Library Manager
2. **File**, **New Project**, **ASP.NET Web Application**, **.NET Core 2.1**.
2. *Shift+Alt+8*, `popper`, **Save manifest file**, **Install**
3. Right click `packman.json`, **Restore Packages**.

I verified this happens in both versions of Visual Studio mentioned, with .NET Core 2.1 projects and 2.0, although I only tested VS 15.6.4 with a .NET Core 2.0 project.

### Current behavior
```
3/31/2018 5:13:59 PM: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.JSON.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.JSON.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at PackmanVsix.PackageService.<IsValidJson>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at PackmanVsix.PackageService.IsValidJson(String file)
   at PackmanVsix.PackageService.<RestorePackagesAsync>d__4.MoveNext() in C:\projects\packman\src\PackmanVsix\PackageService.cs:line 0

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

### Expected behavior
Packages are restored.

**Comment by fredrikhr** [comment] 2018-04-05 15:48
Duplicate of https://github.com/madskristensen/Packman/issues/44

**Closed as completed** 2022-08-01 04:50 UTC
